networks:
  backend_services:

services:
  db:
    image: postgres:17
    container_name: collector_postgres_db
    networks:
    - backend_services
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Windows randomly excluded port 5432 for me, so I had to use 5608 as aquick fix
      - "5608:5432"

  app:
    build: .
    container_name: collector_app
    networks:
      - backend_services
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./screenshots:/screenshots
    env_file:
      - .env.dev
    command: sh -c "python -m app.prestart && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  loki:
    image: grafana/loki:2.4.0
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - backend_services

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - backend_services

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - ./grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - backend_services

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Mount config file
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - backend_services

volumes:
  postgres_data:
  prometheus_data:
